name: API Gateway Deployment

on:
  push:
    branches:
      - master  # Trigger the workflow on push to the master branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    - name: Install dependencies and build
      run: |
        npm install
        npm run build --prod

    - name: Archive build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: |
          ./dist

    - name: Publish build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: deployment-zip
        path: ./dist
